### ISSUE TITLE
To enable fips provider in openssl-3.0.7

### ISSUE THREAD

**Issue by rajivadvait** [kiyolee/openssl3-win-build#1]
How do we enable fips provider in this build. After using the fips enabled build and install command, build of openssl-3.sln is failing. Please suggest the way to enable fips provider in opessl3-win-build. Command used to enable fips
perl Configure VC-WIN32 enable-fips in this path C:\Users\rajiv.tiwari\openssl3-win-build.

**Comment by kiyolee** [comment]
The objective here is only to build default configuration, i.e. without FIPS.
Unless the default configuration changed to support FIPS, there would be no FIPS here.
VS projects/solutions are not the best way to support the hundreds of combinations of configurations that openssl supports.
If you need FIPS, you may need to use the official build method.
Or you need to tweak the property sheets and projects/solutions to support FIPS.
Btw, the solutions/projects here are not to be mixed with official configuration (which I assume you were trying to do).

**Comment by rajivadvait** [comment]
How to tweak the property sheets ? Screen shot attached for reference: 
![image (8)](https://user-images.githubusercontent.com/7310696/209660037-e19db998-012c-4c46-8bb4-6d34703781e5.png)

**Comment by rajivadvait** [comment]
This is not fixed. Looking for your inputs.

**Comment by kiyolee** [comment]
I didn't mean that to be simple. I don't actually know how complex that can be, especially if you want the unit tests to pass.
I'd suggest you build the FIPS support using official method, see official docs.
Alternatively, you may look into using vcpkg instead.
