### ISSUE TITLE
legacy providers are not linked into the static libs

### ISSUE THREAD

**Issue by chaau** [kiyolee/openssl3-win-build#2]
I am linking to openssl statically.

when I try to load the legacy provider programmatically (https://github.com/openssl/openssl/blob/master/README-PROVIDERS.md) using this code:

```
    /* Load Multiple providers into the default (NULL) library context */
    legacy = OSSL_PROVIDER_load(NULL, "legacy");
    if (legacy == NULL) {
        printf("Failed to load Legacy provider\n");
        exit(EXIT_FAILURE);
    }
    deflt = OSSL_PROVIDER_load(NULL, "default");
    if (deflt == NULL) {
        printf("Failed to load Default provider\n");
        OSSL_PROVIDER_unload(legacy);
        exit(EXIT_FAILURE);
    }

```
The OSSL_PROVIDER_load(NULL, "legacy") returns NULL. I feel it is because the legacy providers are not getting linked to the library.

I have researched the Internet and found [here ](https://mta.openssl.org/pipermail/openssl-users/2022-February/014916.html) that in addition to the `no-shared` the `no-module` option must be used.

Can you please advise if it is possible to build it with the no-module option?

**Comment by kiyolee** [comment]
You may need to copy output `legacy.dll` to default install location `C:\Program Files\OpenSSL-3\lib\ossl-modules` for `OSSL_PROVIDER_load()` to work.
As per the `no-module` option, if you need that, you'd need to build openssl using the official build method.
The drawback of VS solution and projects is that it cannot easily support various combinations of options.
The intention here is to build default configuration (as close to default as possible that suit my needs anyway) only.

**Comment by chaau** [comment]
Hi Kelvin,

Thanks for the prompt reply. I am aware about the official build. The reason I decided to have your solution a go is your "Keyboard optional" approach. It is much easier for the team to use this solution compare to the official build.

Can you share how you create all these VS project files, so that you can help me fork it and adjust the perl options.
Have you used any scripts to create these projects, or you have created them all by hand?

**Comment by kiyolee** [comment]
They are all done by hand (until AI is smart enough to replace me).
But if you want to try, you can edit `distfiles\config_all.cmd` and add the options you need.
Extract the source tarball inside `distfiles` and run `config_all.cmd` in there.
Then you compare `configdata.pm` generated in `distfiles` to the ones in `ms` and see what needs to be changed.
I have no idea what `no-module` would impose.
