### ISSUE TITLE
VS version compiler support

### ISSUE THREAD

**Issue by WinserverSupport** [kiyolee/openssl3-win-build#3]
Please excuse the question if its too obvious.   What VS compilers are supported?  Specifically, I am looking for VS 2015 support to allow XP/2003 v140 support.   It appears OpenSSL v3.4 needs VS 2019 at a minimum.   Thank you.

**Comment by kiyolee** [comment]
I do have VS2015 support, actually from VS2013 to VS2022, but only using the default toolset.
I have never tested using the xp toolset for VS2013/VS2015/VS2017.
However, testing that should be simple with my sets of VS projects/solution.
For VS2015, you may do a global search/replace of `<PlatformToolset>v140</PlatformToolset>` with `<PlatformToolset>v140_xp</PlatformToolset>` at the build-VS2015 directory.

I guess the official requirement is to shut off questions about less popular or obsolete platforms.
I am just trying to fill that hole.
While I can successfully run the official testsuites for all the VS builds available in this repo, I cannot guarantee the output binaries would satisfy the original openssl project requirements.

**Comment by WinserverSupport** [comment]
> I do have VS2015 support, actually from VS2013 to VS2022, but only using the default toolset. I have never tested using the xp toolset for VS2013/VS2015/VS2017. However, testing that should be simple with my sets of VS projects/solution. For VS2015, you may do a global search/replace of `<PlatformToolset>v140</PlatformToolset>` with `<PlatformToolset>v140_xp</PlatformToolset>` at the build-VS2015 directory.
> 
> I guess the official requirement is to shut off questions about less popular or obsolete platforms. I am just trying to fill that hole. While I can successfully run the official testsuites for all the VS builds available in this repo, I cannot guarantee the output binaries would satisfy the original openssl project requirements.

Sorry for the delay.  I had resolved this by modifying crypto\threads_win.c to use MSVER <= 1900 instead of 1600.

It compiles with VS2015 and the compiled code works for all Windows OSes including XP/2003.

Thanks

**Comment by kiyolee** [comment]
I guess I see why you need that.
The original code detects Interlocked64 capability by checking compiler version and that is not accurate for your case.
You are indeed using newer compiler but targeting older platforms which does not have Interlocked64 apis.

**Comment by WinserverSupport** [comment]
> I guess I see why you need that. The original code detects Interlocked64 capability by checking compiler version and that is not accurate for your case. You are indeed using newer compiler but targeting older platforms which does not have Interlocked64 apis.

Overall, imv, there was no reason to exclude VS2015 (MSVER 1900)  or even VS2019 (MSVER 1929) compilers.  The conditional compile should be based on the target _WIN32_WINNT only, not __MS_VER, since the xp toolset sets 0x0501 or 0x0502:

#if (defined(_M_IX86) && defined(_WIN32_WINNT) && _WIN32_WINNT <= 0x0502) \
    || (defined(__MINGW32__) && !defined(__MINGW64__))
# define NO_INTERLOCKEDOR64
#endif

This condition should support any vstudio compiler with a v*_xp toolset.

Thanks

**Comment by kiyolee** [comment]
Agree with you. But I don't think the openssl people would accept such changes as PR.
I'd see if I can keep this change local to my repo.

**Comment by sergeevabc** [comment]
Dear @kiyolee, I can't find pre-compiled `openssl.exe` here. You provide sources only?

**Comment by kiyolee** [comment]
@sergeevabc I don't provide prebuilt binaries. You need to build with VS version of your choice.
